alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'
alias aptup='sudo apt update && sudo apt upgrade'
alias apti='sudo apt install'
alias aptcleanup='sudo apt -y purge ?config-files ?garbage && apt search ?obsolete'
alias sc='sudo systemctl'
alias v='nvim'
alias sv='sudo nvim'
alias vim='nvim'
alias smi='sudo make install'
alias xd='fortune -a | cowthink -f $(find /usr/share/cows -type f | shuf -n 1)'
alias starwars='telnet towel.blinkenlights.nl'

